### ISSUE TITLE
Arqbackup connection refused

### ISSUE THREAD

**Issue by mezuky04** [drakkan/sftpgo#1256]
Hello. I'm trying to use SFTPGo with Arqbackup using SFTP as the connection type but I always get a "connection refused" error. I contacted their support and the answer was:

> There's something wrong with this SFTP server. Half the time I try to use I get "connection refused". When it does work, the SFTP server successfully opens a file that does not exist on the server(!) and then returns a generic "failure" error code when Arq tries to read from that file handle.
What it should do is return ENOTFOUND (error code 2) when Arq attempts to open the nonexistent file, like every other SFTP server.

I'm using an S3-compatible storage. Any idea if it's due to a config, or it's something else? Thanks in advance 🙂

**Comment by drakkan** [comment]
Hello,

try posting some SFTPGo logs. Anyway if you get connection refused error maybe the port is wrong or SFTPGo is down (so no other client should work). Please also share your SFTPGo version. Thanks

**Comment by mezuky04** [comment]
Thanks for your quick answer. I'm using `SFTPGo 2.4.3-7d19d3f1-2023-01-07T09:18:58Z +metrics +azblob +gcs +s3 +bolt +mysql +pgsql +sqlite +portable`.

Here are the logs:

```
{"level":"warn","time":"2023-04-07T19:58:14.658","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"stat error for path \"/temp\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: 1753BF5D98BA5AFE, HostID: , api error NotFound: Not Found"}
{"level":"warn","time":"2023-04-07T19:58:14.780","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"stat error for path \"/temp\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: 1753BF5D9FFBFF16, HostID: , api error NotFound: Not Found"}
{"level":"warn","time":"2023-04-07T19:58:15.038","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"stat error for path \"/19F063D7-7091-497B-B531-6CCF2DD43A24/backupfolders.json\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: 1753BF5DAF66E494, HostID: , api error NotFound: Not Found"}
{"level":"warn","time":"2023-04-07T19:58:15.143","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"stat error for path \"/19F063D7-7091-497B-B531-6CCF2DD43A24\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: 1753BF5DB5880274, HostID: , api error NotFound: Not Found"}
{"level":"warn","time":"2023-04-07T19:58:15.263","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"stat error for path \"/19F063D7-7091-497B-B531-6CCF2DD43A24\": operation error S3: HeadObject, https response error StatusCode: 404, RequestID: 1753BF5DBCC177C3, HostID: , api error NotFound: Not Found"}
{"level":"error","time":"2023-04-07T19:58:15.904","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"Unexpected error for transfer, path: \"bau22/19F063D7-7091-497B-B531-6CCF2DD43A24/backupconfig.json\", error: \"operation error S3: GetObject, https response error StatusCode: 404, RequestID: 1753BF5DDFA18183, HostID: afe74956-2012-4db5-8edb-bda3b5506753, NoSuchKey: \" bytes sent: 0, bytes received: 0 transfer running since 62 ms"}
{"level":"error","time":"2023-04-07T19:58:16.035","sender":"SFTP","connection_id":"SFTP_3bb479eb6d93b6622942672b7b3dfb2675756f5bea16a8602e1d4c7f829c1218_1","message":"transfer error: operation error S3: GetObject, https response error StatusCode: 404, RequestID: 1753BF5DDFA18183, HostID: afe74956-2012-4db5-8edb-bda3b5506753, NoSuchKey: , path: \"bau22/19F063D7-7091-497B-B531-6CCF2DD43A24/backupconfig.json\""}
```

Here is the error Arq returns:
<img width="279" alt="image" src="https://user-images.githubusercontent.com/7033003/230672298-adfc19ed-5968-412c-a2e7-7d8fe54c78c2.png">

The root directory of the SFTP user is `bau22/` but I also tried with `/` and it's the same. I'm using IDrive E2 as storage. In case you need an account to test, please let me know 🙂

**Comment by drakkan** [comment]
Hello,

I installed the trial version of Arq in a Windows VM and it works for me (using MinIO as S3 backend)

![Arq](https://user-images.githubusercontent.com/553263/230712332-6e05caba-53f4-4ccd-9b4c-0ab172ed028e.PNG)
![Schermata del 2023-04-08 10-38-46](https://user-images.githubusercontent.com/553263/230712335-b3b940ac-f615-4278-85dd-abff62f5631f.png)

maybe there is some difference between MinIO and IDrive or the Windows version of Arq works differently than the Mac version. Can you please try Arq for Windows like I did? Thanks

**Comment by mezuky04** [comment]
I tested with MinIO in MacOS and it does not work. I also tested it on Windows and it works with both MinIO and IDrive. SFTPGo is not the problem, I will close the issue. Thanks for taking the time to answer 🙂.

**Comment by drakkan** [comment]
I think the Mac client is blindly trying to open the file without doing a stat or a list dir first (as all other clients do, so does their Windows version). 
If you are using the local filesystem as the SFTPGo backend, the open will fail and SFTPGo will return the error expected by Arqbackup, but with a cloud backend things are different, the file is accessed on first read.

I just pushed this [commit](https://github.com/drakkan/sftpgo/commit/429465978592d035cc91b2243e7fdfc7099795df) where SFTPGo tries to convert generic read errors in well-known error types. After this change if you try blindly opening a missing file on a Cloud backend, SFTPGo will return a not found error (error code 2 for the SFTP protocol) after the first read.
I'm not sure if this is enough to make the Arq Mac version work. Adding a stat call (read an additional http request to the cloud provider) before each download would degrade performance too much. 
Many sftp servers using cloud backends behave like SFTPGo, not many SFTP clients behave like Arqbackup for Mac

**Comment by mezuky04** [comment]
When do you plan to release v2.4.5? I will test to see if it fixed the problem with Arq for Mac

**Comment by drakkan** [comment]
> When do you plan to release v2.4.5? I will test to see if it fixed the problem with Arq for Mac

Just released

**Comment by mezuky04** [comment]
I tested on MacOS and the problem still appears. I will leave the issue closed because the Arq app on MacOS behaves differently compared to the Windows version. Thanks again for checking 🙂

**Comment by drakkan** [comment]
> I tested on MacOS and the problem still appears. I will leave the issue closed because the Arq app on MacOS behaves differently compared to the Windows version. Thanks again for checking slightly_smiling_face

so they expect to receive the error on open, as explained they should do a stat instead as on Windows. If you use the local storage instead of S3 I think Arqbackup will work. Doing an additional stat before each download on the SFTPGo side will greatly affect performance
