### ISSUE TITLE
S3 storage - renaming not working

### ISSUE THREAD

**Issue by spmfox** [drakkan/sftpgo#483]
Hello, great project - just testing it out.

I'm having an issue renaming files using S3 as the storage.

```
Jul 20 21:01:44 892e88aa5bf1 sftpgo[20]: {"level":"debug","time":"2021-07-20T21:01:44.845","sender":"SFTP","connection_id":"SFTP_af58e084bff4b9871d79353650f60ff11e0d96d3dc831f1a8f19eb7e673a577a_1","message":"new cmd, method: Rename, sourcePath: \"/README\", targetPath: \"/test\""}

Jul 20 21:01:45 892e88aa5bf1 sftpgo[20]: {"level":"warn","time":"2021-07-20T21:01:45.185","sender":"SFTP","connection_id":"SFTP_af58e084bff4b9871d79353650f60ff11e0d96d3dc831f1a8f19eb7e673a577a_1","message":"failed to rename \"/README\" -> \"/test\": InvalidArgument: \n\tstatus code: 400, request id: tx0000000000000076448d0-0060f739b9-263f782-default, host id: "}
```

At first I thought the problem was just "moving" files in between directories, but I see now that all renames are not working. I tried this via FileZilla and the sftp command line, same result. I am using Linode object storage as the S3 backend.

Any idea what could be wrong?

**Comment by drakkan** [comment]
Hi,

I have no way to test SFTPGo with Linode, sorry. To rename objects we use the AWS [CopyObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html) API, see [here](https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L291). Rename works fine with real S3, MinIO and many others S3 compatible object storage. 

You could ask to Linode support linking this issue, maybe they can help or you can grant me some Linode credentials for testing (I'm quite busy but I'll try to find some time). 

Do you know if Linode object storage is based on Ceph or some other open source S3 implementation that I can try on my own at no cost? Thank you

**Comment by spmfox** [comment]
@drakkan I *believe* they are using Ceph but I'm not sure. I just tried with Digital Ocean Spaces as well and the results are the same.

I tested manually like this
```
aws --endpoint-url https://us-east-1.linodeobjects.com s3 cp s3://bucket/README s3://bucket/test/README
```
And this was successful, per the documentation the 'aws s3' command should be using CopyObject in the background. Is there any way to get the actual response from the server that was the error? The only clue is the "InvalidArgument: \n\tstatus code: 400" part.

**Comment by spmfox** [comment]
The only thing remotely similar I've found on the internet is this:

https://github.com/kahing/goofys/issues/46
https://github.com/aws/aws-sdk-go/issues/400
https://github.com/aws/aws-sdk-go/issues/2212

Do you think its possibly related? Those issues are a bit old.

**Comment by drakkan** [comment]
Hi,

SFTPGo does not support v2 signatures. The error in the logs is the one returned from the AWS SDK, maybe we could get more info enabling the SDK debug logs.

I'm not sure if this helps, anyway can you please try to disable path style [here](https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L87)? I don't have any of these accounts, sorry

**Comment by spmfox** [comment]
Okay so I *think* I was able to disable it, I've never compiled go and honestly I'm new at compiling anything. I cloned the current branch, edited the code, built it with the latest golang container, and grabbed that executable and tried - same results. It's possible I did something wrong, but my executable worked so I'm not sure.

How do I enable the SDK debug logs? I really know nothing of the AWS SDK sorry.

**Comment by drakkan** [comment]
Hi,

to enable logging add this line

```
awsConfig.LogLevel = aws.LogLevel(aws.LogDebug)
```
after `awsConfig := aws.NewConfig()` [here](https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L72)

To compile the sw (assuming you are on Linux), clone the repo, install Go 1.16.6 and then from the repo directory use the following command:

```shell
go build -ldflags "-s -w" -o sftpgo
```

you can now start sftpgo this way:

```shell
./sftpgo serve -l ""
```

with SDK logs enabled I have these info when renaming a file:

```
2021/07/21 19:52:46 DEBUG: Request s3/CopyObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
PUT /test/b.txt HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=Server-Access-Key/20210721/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-copy-source;x-amz-date, Signature=e9240baabdd34c2611d72afbc3039d24619ea0a5f2e589d2c065c1c55e216e7b
Content-Type: text/plain; charset=utf-8
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Copy-Source: test%2Fa.txt
X-Amz-Date: 20210721T175246Z
Accept-Encoding: gzip


-----------------------------------------------------
2021/07/21 19:52:46 DEBUG: Response s3/CopyObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Content-Length: 232
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Wed, 21 Jul 2021 17:52:46 GMT
Etag: "cdba7a6fb2ec1f219df1a117c79dd48e"
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1693DFCE07BA7A90
X-Xss-Protection: 1; mode=block


-----------------------------------------------------
2021/07/21 19:52:46 DEBUG: Request s3/DeleteObject Details:
---[ REQUEST POST-SIGN ]-----------------------------
DELETE /test/a.txt HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
Authorization: AWS4-HMAC-SHA256 Credential=Server-Access-Key/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f314f0139c985cefc9a04aaa53afc221e4b5c8038e704a3af6909f910e97b521
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210721T175246Z
Accept-Encoding: gzip


-----------------------------------------------------
2021/07/21 19:52:46 DEBUG: Response s3/DeleteObject Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 204 No Content
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Date: Wed, 21 Jul 2021 17:52:46 GMT
Server: MinIO
Vary: Origin
X-Amz-Request-Id: 1693DFCE08AD34F9
X-Xss-Protection: 1; mode=block
```

**Comment by spmfox** [comment]
Okay, the compile worked, this is an example of renaming a file from README -> README2

```
{"level":"debug","time":"2021-07-21T19:01:46.211","sender":"SFTP","connection_id":"SFTP_18820a2beca089df2c7b08f075aeb98e00c0a37333f41f55955db0478ce474c3_1","message":"new cmd, method: Rename, sourcePath: \"/README\", targetPath: \"/README2\""}
 2021/07/21 19:01:46 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0fa8d6a09b4617b0aaa5dd7ba5aeaff3ed4f1c7d4917c349b021bea549a52551
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T190146Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Content-Length: 4430
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: binary/octet-stream
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 Etag: "b50a3c41497fb16429ec8bb8c66fdd7c"
 Last-Modified: Tue, 20 Jul 2021 20:52:41 GMT
 X-Amz-Request-Id: tx0000000000000082f28e3-0060f86f1a-263f67e-default
 X-Rgw-Object-Type: Normal
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README2 HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=dd1b82760eed957edb609a4e421593d8e6296f8d4faecdc769e143d87198aab1
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T190146Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 404 Not Found
 Content-Length: 220
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 X-Amz-Request-Id: tx0000000000000085230d1-0060f86f1a-263a001-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Request s3/ListObjectsV2 Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 GET /sp-test?list-type=2&max-keys=2&prefix=README2%2F HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=fc0f48c624b0bb65e537a2b5a2f92ee662de656cb5cc7aae3d2bf7ff51732191
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T190146Z
 Accept-Encoding: gzip
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/ListObjectsV2 Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Transfer-Encoding: chunked
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 X-Amz-Request-Id: tx000000000000008304d30-0060f86f1a-263fa98-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README2/ HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4c9741d4bec33fa8a7e46f8280afb68ad3831b89dd5b8fe84ea8b9aecbf340ce
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T190146Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 404 Not Found
 Content-Length: 220
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 X-Amz-Request-Id: tx000000000000008304d3d-0060f86f1a-263fa98-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=0fa8d6a09b4617b0aaa5dd7ba5aeaff3ed4f1c7d4917c349b021bea549a52551
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T190146Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Content-Length: 4430
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: binary/octet-stream
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 Etag: "b50a3c41497fb16429ec8bb8c66fdd7c"
 Last-Modified: Tue, 20 Jul 2021 20:52:41 GMT
 X-Amz-Request-Id: tx00000000000000840f68d-0060f86f1a-264048f-default
 X-Rgw-Object-Type: Normal
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Request s3/CopyObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 PUT /sp-test/README2 HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Content-Length: 0
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date, Signature=fa2b1d8ed3c3ba73585419a4e7a218e6110f0271fe581812ca0b3169b90b359b
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Copy-Source: sp-test%2FREADME
 X-Amz-Date: 20210721T190146Z
 Accept-Encoding: gzip
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 19:01:46 DEBUG: Response s3/CopyObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 400 Bad Request
 Content-Length: 194
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 19:01:46 GMT
 X-Amz-Request-Id: tx000000000000008305375-0060f86f1a-263b136-default
 [1B blob data]
 -----------------------------------------------------
 {"level":"warn","time":"2021-07-21T19:01:46.638","sender":"SFTP","connection_id":"SFTP_18820a2beca089df2c7b08f075aeb98e00c0a37333f41f55955db0478ce474c3_1","message":"failed to rename \"/README\" -> \"/README2\": InvalidArgument: \n\tstatus code: 400, request id: tx000000000000008305375-0060f86f1a-263b136-default, host id: "}
```

**Comment by drakkan** [comment]
This does not help, please compile again using this log line

```
awsConfig.LogLevel = aws.LogLevel(aws.LogDebugWithHTTPBody)
```

maybe the copy object response body contains more info. Thank you, your help is very appreciated

**Comment by spmfox** [comment]
No problem, I appreciate your help. What do you think of these logs?

```
{"level":"debug","time":"2021-07-21T20:10:15.640","sender":"SFTP","connection_id":"SFTP_d7091b0f487aea319b7fc3989367fef753b76547dc583af61cd2c2bf41f92e43_1","message":"new cmd, method: Rename, sourcePath: \"/README\", targetPath: \"/README2\""}
 2021/07/21 20:10:15 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=82cfdaf97d2ed3ac486df32f6e76f2cad49e29476d22cb016da2bc1999672c84
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T201015Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Content-Length: 4430
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: binary/octet-stream
 Date: Wed, 21 Jul 2021 20:10:15 GMT
 Etag: "b50a3c41497fb16429ec8bb8c66fdd7c"
 Last-Modified: Tue, 20 Jul 2021 20:52:41 GMT
 X-Amz-Request-Id: tx0000000000000083e6445-0060f87f27-263b717-default
 X-Rgw-Object-Type: Normal
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15
 2021/07/21 20:10:15 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README2 HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=44a154d8f498b03ec6556ac0c71242414885d9d170b40a20e52a16228169458a
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T201015Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 404 Not Found
 Content-Length: 220
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 20:10:15 GMT
 X-Amz-Request-Id: tx0000000000000083a0f3f-0060f87f27-263b825-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15
 2021/07/21 20:10:15 DEBUG: Request s3/ListObjectsV2 Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 GET /sp-test?list-type=2&max-keys=2&prefix=README2%2F HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=cbc5e2455fdd1bde91d740c16100d3791e01d26218175b525a5bcb87abcb526c
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T201015Z
 Accept-Encoding: gzip
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15 DEBUG: Response s3/ListObjectsV2 Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Transfer-Encoding: chunked
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 20:10:15 GMT
 X-Amz-Request-Id: tx000000000000008329c9e-0060f87f27-263f57f-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15 <?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>sp-test</Name><Prefix>README2/</Prefix><MaxKeys>2</MaxKeys><IsTruncated>false</IsTruncated><KeyCount>0</KeyCount></ListBucketResult>
 2021/07/21 20:10:15 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README2/ HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=8570cbee881f984eac20da67ab531d7a0b8c7aabc5b6f3238b7dd6bbdfc7f23f
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T201015Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 404 Not Found
 Content-Length: 220
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 20:10:15 GMT
 X-Amz-Request-Id: tx0000000000000084b1492-0060f87f27-2640665-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:15
 2021/07/21 20:10:15 DEBUG: Request s3/HeadObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 HEAD /sp-test/README HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=82cfdaf97d2ed3ac486df32f6e76f2cad49e29476d22cb016da2bc1999672c84
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Date: 20210721T201015Z
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:16 DEBUG: Response s3/HeadObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 200 OK
 Content-Length: 4430
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: binary/octet-stream
 Date: Wed, 21 Jul 2021 20:10:16 GMT
 Etag: "b50a3c41497fb16429ec8bb8c66fdd7c"
 Last-Modified: Tue, 20 Jul 2021 20:52:41 GMT
 X-Amz-Request-Id: tx000000000000008345a48-0060f87f27-263f67e-default
 X-Rgw-Object-Type: Normal
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:16
 2021/07/21 20:10:16 DEBUG: Request s3/CopyObject Details:
 ---[ REQUEST POST-SIGN ]-----------------------------
 PUT /sp-test/README2 HTTP/1.1
 Host: us-east-1.linodeobjects.com
 User-Agent: aws-sdk-go/1.40.3 (go1.16.6; linux; amd64)
 Content-Length: 0
 Authorization: AWS4-HMAC-SHA256 Credential=UDC8IGZQL1ZB1CNOB9SO/20210721/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date, Signature=0f4c4900c42b000ccc28a9cfda5af2a6f3e6b6c5a6007fc602ea3e38f2545759
 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 X-Amz-Copy-Source: sp-test%2FREADME
 X-Amz-Date: 20210721T201016Z
 Accept-Encoding: gzip
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:16 DEBUG: Response s3/CopyObject Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 400 Bad Request
 Content-Length: 194
 Accept-Ranges: bytes
 Connection: keep-alive
 Content-Type: application/xml
 Date: Wed, 21 Jul 2021 20:10:16 GMT
 X-Amz-Request-Id: tx00000000000000835a8b0-0060f87f28-263b136-default
 [1B blob data]
 -----------------------------------------------------
 2021/07/21 20:10:16 <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><RequestId>tx00000000000000835a8b0-0060f87f28-263b136-default</RequestId><HostId>263b136-default-default</HostId></Error>
 {"level":"warn","time":"2021-07-21T20:10:16.158","sender":"SFTP","connection_id":"SFTP_d7091b0f487aea319b7fc3989367fef753b76547dc583af61cd2c2bf41f92e43_1","message":"failed to rename \"/README\" -> \"/README2\": InvalidArgument: \n\tstatus code: 400, request id: tx00000000000000835a8b0-0060f87f28-263b136-default, host id: "}
```

**Comment by drakkan** [comment]
well the error is:

```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidArgument</Code><RequestId>tx00000000000000835a8b0-0060f87f28-263b136-default</RequestId><HostId>263b136-default-default</HostId></Error>
```

so there is a generic invalid argument, we have to try ...

try to change this [line](https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L293):

```
CopySource:   aws.String(url.PathEscape(copySource))
```

to

```
CopySource:   aws.String(copySource)
```

you likely have to remove this [line](https://github.com/drakkan/sftpgo/blob/main/vfs/s3fs.go#L9) to be able to compile

if we have to add a new argument insteof of replacing an existing one is more difficult. It is a bit late at my timezone, I'll take a look at you reply tomorrow, thank you.

P.S. please execute a copy object from s3 cli with debug enabled so we compare the copy object requests

**Comment by spmfox** [comment]
This fixed the problem, I can now rename and move (rename) files into new directories.

So what does this mean long-term, is there a reason to have this URL style vs the one you had originally? Is this something that can be added and toggled in the S3 GUI settings?

Also, do you have a PayPal to your email for donations? I saw the crypto donations but was curious about PayPal.

**Comment by drakkan** [comment]
Hi,

if we remove that line renames with non-ascii chars will fail on AWS S3, see #257 for more details. Can you please confirm that now renames also work with non-ascii characters on Linode?

The official AWS SDK example uses [path escape](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/go/example_code/s3/s3_copy_object.go#L65), so this seems a bug in Linode (Ceph?) S3 implementation.

Yesterday I tested using seaweedfs and it has no issue. The next weekend I'll try to find time to install Ceph and test against it. If I can replicate the issue I'll report a bug upstream and then decide whether to add a new setting to control this behavior.

Maybe you could try to report a bug to Linode guys, I'm not sure if they just install an open source S3 gateway or if they are able to fix bugs too.

Here is my [PayPal](https://www.paypal.com/donate?hosted_button_id=JQL6GBT8GXRKC) account, thank you

**Comment by spmfox** [comment]
I just tested, yes non-ascii renames work with the same fix on Linode. I renamed a file from test -> 网络 and it worked. So weird that "S3 compatible" is not really a firm standard, because clearly it is not fully compatible when stacking up to real S3.

Linode uses Ceph and so does Digital Ocean, which also encountered the same problem during my testing. I would have no problems contacting Linode support, I'm sure they'd be interested, however without a firm understanding of what actually is failing I'm hesitant to just point them at this GitHub issue. Plus the fact that it doesn't work on Digital Ocean as well.

If you cant reproduce it yourself, I can give you credentials to a test bucket if you want to try yourself on Linode.

**Comment by drakkan** [comment]
Please take a look at the AWS docs [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html). It explictly says that `x-amz-copy-source` must be URL encoded. We are removing url encoding and this will not work with AWS S3. This is the bug to report to Ceph/Linode.

I have some ideas to workaround this issue (but an upstream fix would be better anyway), for example I can URL encode the path components but not the separator (the `/`), this works with S3. If you can send me some test credentials to my private email (the one you see in each Git commit) this will speedup my tests. I'll just upload some small files to test renames. Thank you

**Comment by spmfox** [comment]
I sent the credentials, check your spam folder because Gmail doesn't like my mail server.

Thank you again.

**Comment by drakkan** [comment]
I received the credentials, thank you.

This bug was fixed in Ceph some days ago:

https://tracker.ceph.com/issues/43259
https://github.com/ceph/ceph/pull/42126

As you can see from the above patch diff, the old code searchs for `/` in the copy source but since it is url encoded as `%2F` it fails.  They now added `std::string dec_src = url_decode(name_str);` that fixes the issue.

Since this fix is not in any released Ceph version yet, I'll try to find a temporary workaround.

**Comment by drakkan** [comment]
This should work now. You can test using one of the latest edge docker images or by downloading a build artifact from [here](https://github.com/drakkan/sftpgo/actions/runs/1059236098). Thank you

**Comment by mtfelian** [comment]
> 
> to enable logging add this line
> 

Did this in latest version of sftpgo. 

File `vfs/s3fs.go` in `func NewS3Fs`

may be done in the following way: 
```
awsConfig, err := config.LoadDefaultConfig(ctx, config.WithHTTPClient(getAWSHTTPClient(0, 30*time.Second)),
		config.WithClientLogMode(aws.LogRequest|aws.LogResponse))
```

**Comment by drakkan** [comment]
> > to enable logging add this line
> 
> Did this in latest version of sftpgo.
> 
> File `vfs/s3fs.go` in `func NewS3Fs`
> 
> may be done in the following way:
> 
> ```
> awsConfig, err := config.LoadDefaultConfig(ctx, config.WithHTTPClient(getAWSHTTPClient(0, 30*time.Second)),
> 		config.WithClientLogMode(aws.LogRequest|aws.LogResponse))
> ```
> 
> according to docs: https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/logging/
> 
> Proved locally.

Yes, SFTPGo main branch now uses aws sdk v2, instructions here were for aws sdk v1 used in previous versions

**Comment by x6nl** [comment]
Hi the rename/move problem still exists with very large files. We do not have it with smaller files but for instance a file over 3GB does not move on the S3 storage.

**Comment by drakkan** [comment]
> Hi the rename/move problem still exists with very large files. We do not have it with smaller files but for instance a file over 3GB does not move on the S3 storage.

You're having a different issue, see #899 it is already fixed

https://github.com/drakkan/sftpgo/commit/756b122ab8041ab3fb04ef4f45b2a589bf3440ca
https://github.com/drakkan/sftpgo/commit/d3d788c8d02da564c5e3db854abedec71b08443a

but it is not yet included in any stable release. 
Tagging a new version requires some manual work and unfortunately I don't have enough free time in this period, for now use the develpoment version or the 2.3.x branch. Or consider helping the project with a [sponsorship/donations](https://github.com/drakkan/sftpgo#sponsors) that enable me to spend more time working on SFTPGo, thank you
